name = "sogotable-api"
main = "workers/sogotable-api.js"
compatibility_date = "2026-06-07"
account_id = "d8daaab7a2e7af2cce387d9b9df3c8d3"

routes = [
  { pattern = "sogotable.sogodojo.com/api/*", zone_name = "sogodojo.com" }
]

[[d1_databases]]
binding = "SOGOTABLE_STATE"
database_name = "sogotable-state"
database_id = "bbb1cdec-0410-476f-b058-f216263b61d8"

[[ratelimits]]
name = "API_MUTATION_RATE_LIMITER"
namespace_id = "1001"
simple = { limit = 180, period = 60 }

[[ratelimits]]
name = "SUPERUSER_RATE_LIMITER"
namespace_id = "1002"
simple = { limit = 20, period = 60 }

[[durable_objects.bindings]]
name = "ROOM_OBJECT"
class_name = "RoomDurableObject"

[[durable_objects.bindings]]
name = "ROOM_FACTORY"
class_name = "RoomFactoryDurableObject"

[[durable_objects.bindings]]
name = "EVENT_HUB"
class_name = "EventHubDurableObject"

[[migrations]]
tag = "v1_room_durable_object"
new_sqlite_classes = [ "RoomDurableObject" ]

[[migrations]]
tag = "v2_event_hub"
new_sqlite_classes = [ "EventHubDurableObject" ]

[[migrations]]
tag = "v3_room_factory"
new_sqlite_classes = [ "RoomFactoryDurableObject" ]
